# Observability kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./rancher-logging
  - ./rancher-monitoring

# Teach kustomize how to update generated names
configurations:
  - kustomizeconfig.yaml

# components:
  # - ../../components/generators/ssl-certificates

  # Update resources based on ConfigMap above
  # - ../../components/config-matcher

  # Required for VaultAuth role and service accounts
  # - ../../components/generators/vault-auth
