---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster.yaml # pg-core Cluster
  - namespace.yaml

  - ./apps-shared-db-credentials.yaml
  - ./cnpg-vault-auth.yaml

  - ../app-databases/

  # - pgbouncer-pooler.yaml     # not yet used

namespace: postgres

#configMapGenerator:
#  - name: tcp-services
#    namespace: kube-system
#    literals:
#      - "5432=postgres/pg-core-rw:5432"
