---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bootstrap-app-privileges.yaml              # bootstrap job to init DB
  - cluster.yaml                      # pg-core Cluster
  - default-privileges.yaml  # generic SQL used by bootstrap job
  - namespace.yaml
  - ../app-databases/
  # - pgbouncer-pooler.yaml     # not yet used

namespace: postgres

#configMapGenerator:
#  - name: tcp-services
#    namespace: kube-system
#    literals:
#      - "5432=postgres/pg-core-rw:5432"
