# Deploys Ingress resources
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: primary-ingress
  namespace: course-production-site
spec:
  tls:
    - hosts:
        - course-production.ltc.bcit.ca
      secretName: star-ltc-bcit-ca
  rules:
    - host: course-production.ltc.bcit.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 8080
