# Deploys a chart release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-release
spec:
  interval: 24h
  releaseName: alloy
  chart:
    spec:
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: grafana-helm-repository
      # version: ""  # (optional) pin a chart version later
  values:
    controller:
      type: daemonset

    alloy:
      configMap:
        create: false
        name: values
        key: config
