# Infrastructure kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./alloy
  - ./grafana
  - ./loki
  - helm-repository.yaml
  - namespace.yaml
  # - backupstore-azblob.enc.yaml (TODO: pull from Vault instead)

# Replace base Namespace name and add all resources to this namespace
namespace: observability

# Source Chart Repo
  # url: https://releases.rancher.com/server-charts/stable

# Teach kustomize how to update generated names
configurations:
  - kustomizeconfig.yaml

# components:
  # - ../../components/generators/ssl-certificates

  # Update resources based on ConfigMap above
  # - ../../components/config-matcher

  # Required for VaultAuth role and service accounts
  # - ../../components/generators/vault-auth

