# legacy-soc-php kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - namespace.yaml

# Prefix all resources with this name
namePrefix: legacy-soc-php-

# Replace base Namespace name and add all resources to this namespace
namespace: legacy-soc-php

# Generate a re-usable name variable for other resources
configMapGenerator:
  - name: release-name
    literals:
      - releaseName="legacy-soc-php"

    # Resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

# Order matters!
components:
  # Configure GitHub webhook for reconciling cluster resources when repo is updated
  - ../../components/notifications

  # Add GitHub tokens for private repos/packages
  - ../../components/github-private-tokens

  # Add TLS certificates for ingress
  - ../../components/ssl-certificates

  # Add Vault authentication (role and service accounts)
  - ../../components/vault-auth

  # Update resources based on release name (ConfigMap above)
  - ../../components/config-matcher
