# qcon-web kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  # required secrets are managed by qcon-api

# Prefix all resources with this name
namePrefix: qcon-web-

# Replace base Namespace name and add all resources to this namespace
namespace: qcon

# Generate a re-usable name variable for other resources
configMapGenerator:
  - name: release-name
    literals:
      - releaseName="qcon-web"

    # Resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

# Order matters!
components:
  # Configure GitHub webhook for reconciling cluster resources when repo is updated
  # - ../../../components/notifications

  # Add TLS certificates for ingress
  - ../../../components/ssl-star-latest-ltc-bcit-ca
  - ../../../components/ssl-star-ltc-bcit-ca

  # Add Vault authentication (role and service accounts)
  - ../../../components/vault-auth

  # Update resources based on release name (ConfigMap above)
  - ../../../components/config-matcher
