# qcon-web kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  # managed by qcon-api
  # - api-key.yaml
  # - app-internal-credentials.yaml
  # - db-credentials.yaml     # Also see VaultDynamicSecret patch below

# Prefix all resources with this name
namePrefix: qcon-web-

# Replace base Namespace name and add all resources to this namespace
namespace: qcon

# Generate a re-usable name variable for other resources
configMapGenerator:
  - name: release-name
    literals:
      - releaseName="qcon-web"

    # Resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

# Order matters!
components:
  # Configure GitHub webhook for reconciling cluster resources when repo is updated
  # - ../../components/notifications

  # Add Vault authentication (role and service accounts)
  - ../../../components/vault-auth

  # Update resources based on release name (ConfigMap above)
  - ../../../components/config-matcher

patches:
  - target:
      kind: Namespace
      name: qcon-web
    patch: |
      $patch: delete
      kind: Namespace
      metadata:
        name: DOES NOT MATTER

  - target:
      kind: VaultDynamicSecret
    patch: |-
      - op: replace
        path: /spec/path
        value: creds/qcon-web
      - op: replace
        path: /metadata/annotations/app~1db-name
        value: qcon_web
