---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster.yaml                      # pg-core Cluster
  - default-privs-sql-configmap.yaml  # generic SQL used by bootstrap job
  - namespace.yaml
  #
  # NOTE: we do NOT include bootstrap-app-privs-job.yaml here,
  #       so Jobs only run when you explicitly kubectl apply them.

  # - pgbouncer-pooler.yaml     # not yet used
  # - postgres-vault-auth.yaml

namespace: postgres

#configMapGenerator:
#  - name: tcp-services
#    namespace: kube-system
#    literals:
#      - "5432=postgres/pg-core-rw:5432"
