---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster.yaml        # pg-core Cluster
  - namespace.yaml
  - default-privs-sql-configmap.yaml  # generic SQL used by bootstrap job
  #
  # NOTE: we do NOT include bootstrap-app-privs-job.yaml here,
  #       so Jobs only run when you explicitly kubectl apply them.

  # - pgbouncer-pooler.yaml     # not yet used
  - postgres-vault-auth.yaml

namespace: postgres
