additionalLoggingSources:
  aks:
    enabled: false
  eks:
    enabled: false
  gke:
    enabled: false
  k3s:
    container_engine: systemd
    enabled: false
    stripUnderscores: false
  kubeAudit:
    auditFilename: ''
    enabled: false
    fluentbit:
      logTag: kube-audit
      tolerations: []
    pathPrefix: ''
  rke:
    enabled: false
    fluentbit:
      log_level: info
      mem_buffer_limit: 5MB
  rke2:
    enabled: true
    stripUnderscores: false
affinity: {}
annotations: {}
createCustomResource: false
debug: false
disablePvc: true
dnsConfig: {}
env: []
extraArgs:
  - '-enable-leader-election=true'
extraManifests: []
fluentbit:
  filterKubernetes:
    Merge_Log: ''
    Merge_Log_Key: ''
    Merge_Log_Trim: ''
    Merge_Parser: ''
  inputTail:
    Buffer_Chunk_Size: ''
    Buffer_Max_Size: ''
    Mem_Buf_Limit: ''
    Multiline_Flush: ''
    Skip_Long_Lines: ''
  metrics:
    prometheusRules: false
    serviceMonitor: false
  podPriorityClassName: ''
  resources: {}
  tolerations: []
fluentd:
  bufferStorageVolume: {}
  env: []
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    tcpSocket:
      port: 24240
  logLevel: {}
  metrics:
    prometheusRules: false
    serviceMonitor: false
  nodeSelector: {}
  podPriorityClassName: ''
  resources: {}
  tolerations: {}
fullnameOverride: ''
global:
  cattle: {}
  dockerRootDirectory: ''
  rkeWindowsPathPrefix: c:\
  seLinux:
    enabled: false
http:
  port: 8080
  service:
    annotations: {}
    clusterIP: None
    labels: {}
    type: ClusterIP
image:
  pullPolicy: IfNotPresent
  repository: rancher/mirrored-kube-logging-logging-operator
  tag: 4.10.0
imagePullSecrets: []
images:
  config_reloader:
    repository: rancher/mirrored-kube-logging-config-reloader
    tag: v0.0.6
  fluentbit:
    repository: rancher/mirrored-fluent-fluent-bit
    tag: 3.1.8
  fluentbit_debug:
    repository: rancher/mirrored-fluent-fluent-bit
    tag: 3.1.8-debug
  fluentd:
    repository: rancher/mirrored-kube-logging-fluentd
    tag: v1.16-4.10-full
  nodeagent_fluentbit:
    os: windows
    repository: rancher/fluent-bit
    tag: 3.1.8
logging:
  allowClusterResourcesFromAllNamespaces: false
  clusterDomain: cluster.local.
  clusterFlows: []
  clusterOutputs: []
  configCheck: {}
  controlNamespace: ''
  defaultFlow: {}
  enableDockerParserCompatibilityForCRI: false
  enableRecreateWorkloadOnImmutableFieldChange: false
  enabled: false
  errorOutputRef: ''
  eventTailer:
    containerOverrides: null
    enabled: false
    image:
      imagePullSecrets: []
      pullPolicy: null
      repository: null
      tag: null
    name: event-tailer
    pvc:
      accessModes:
        - ReadWriteOnce
      enabled: false
      storage: 1Gi
      storageClassName: null
      volumeMode: Filesystem
    workloadMetaOverrides: null
    workloadOverrides: null
  flowConfigCheckDisabled: false
  flowConfigOverride: ''
  fluentbit: {}
  fluentbitDisabled: false
  fluentd: {}
  fluentdDisabled: false
  globalFilters: []
  hostTailer:
    enabled: false
    fileTailers: []
    image:
      imagePullSecrets: []
      pullPolicy: null
      repository: null
      tag: null
    name: hosttailer
    systemdTailers: []
    workloadMetaOverrides: null
    workloadOverrides: null
  loggingRef: ''
  nodeAgents: {}
  skipInvalidResources: false
  syslogNG: {}
  watchNamespaceSelector: {}
  watchNamespaces: []
loggingServiceAccountAnnotations: {}
monitoring:
  serviceMonitor:
    additionalLabels: {}
    enabled: false
    metricRelabelings: []
    relabelings: []
nameOverride: ''
namespaceOverride: ''
nodeAgents:
  tls:
    enabled: false
nodeSelector: {}
podLabels: {}
podSecurityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000
priorityClassName: {}
rbac:
  createAggregatedEditClusterRole: false
  enabled: true
replicaCount: 1
resources: {}
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
serviceAccount:
  annotations: {}
systemdLogPath: /run/log/journal
testReceiver:
  enabled: false
  image: fluent/fluent-bit
  port: 8080
  pullPolicy: IfNotPresent
  service:
    annotations: {}
    clusterIP: None
    labels: {}
    type: ClusterIP
tolerations: []
volumeMounts: []
volumes: []
