# Deploys Ingress resources
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-env
  annotations:
    app: flux
spec:
  tls:
    - hosts:
        - flux.env.ltc.bcit.ca
      secretName: star-ltc-bcit-ca
  rules:
    - host: flux.env.ltc.bcit.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webhook-receiver
                port:
                  number: 8080
