# Deploys a chart release
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-release
spec:
  interval: 24h
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-helm-repository
  valuesFrom:
    - kind: ConfigMap
      name: values
      valuesKey: values.yaml
    - kind: Secret
      name: secrets
      valuesKey: adminPassword
      targetPath: adminPassword
