# Infrastructure kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-release.yaml

namespace: observability

# Prefix all resources with this name
namePrefix: loki-

# Generate a re-usable name variable for other resources
configMapGenerator:
  - name: release-name
    literals:
      - releaseName="loki"

    # This config resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"
