apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./qcon-api
  - ./qcon-web
  - ./qcon-guide
  - namespace.yaml

components:
  # Vault token to decrypt secrets
  # - ../../../components/sops-vault-token

  # Add TLS certificates for ingress
  - ../../components/ssl-star-latest-ltc-bcit-ca
  - ../../components/ssl-star-ltc-bcit-ca
