# Flux Kustomization deployments
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-secrets-operator.yaml
  - flux-extra.yaml
  - longhorn.yaml
  - cloudnative-pg.yaml
  - apps.yaml
  - legacy-apps.yaml
