# Flux Kustomization deployments
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 0-vault-secrets-operator.yaml
  - 1-tailscale.yaml
  - 2-flux-extra.yaml
  - 3-longhorn.yaml
  - 4-cloudnative-pg.yaml
  - 5-apps.yaml
