# dataset-retriever kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - namespace.yaml

# Prefix all resources with this name
namePrefix: dataset-retriever-

# Replace base Namespace name and add all resources to this namespace
namespace: dataset-retriever

# Generate a re-usable name variable for other resources
configMapGenerator:
  - name: release-name
    literals:
      - releaseName="dataset-retriever"

    # Resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

# Order matters!
components:
  # Add Vault authentication (role and service accounts)
  - ../../components/vault-auth

  # Update resources based on release name (ConfigMap above)
  - ../../components/config-matcher
