# Configure an ingress
---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ingress.yaml

# Teach kustomize how to update generated names
# configurations:
#   - kustomizeconfig.yaml
