# qcon-api kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - api-key.yaml
  - app-internal-credentials.yaml
  - db-credentials.yaml # Also see VaultDynamicSecret patch below

# Prefix all resources with this name
namePrefix: qcon-api-

# Replace base Namespace name and add all resources to this namespace
namespace: qcon

# Generate a re-usable name variable for other resources
configMapGenerator:
  - name: release-name
    literals:
      - releaseName="qcon-api"

    # Resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

# Order matters!
components:
  # Configure GitHub webhook for reconciling cluster resources when repo is updated
  # - ../../../components/notifications

  # Add TLS certificates for ingress
  - ../../../components/ssl-certificates

  # Add Vault authentication (role and service accounts)
  - ../../../components/vault-auth

  # Update resources based on release name (ConfigMap above)
  - ../../../components/config-matcher

patches:
  # Special patch for apps with dynamic secrets
  - target:
      kind: VaultDynamicSecret
    patch: |-
      - op: replace
        path: /spec/path
        value: creds/qcon-api
      - op: replace
        path: /metadata/annotations/app~1db-name
        value: qcon_api
