# Infrastructure kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-release.yaml
  - helm-repository.yaml
  - longhorn-vault-auth.yaml
  - longhorn-azblob-credentials.yaml
  - namespace.yaml

# Replace base Namespace name and add all resources to this namespace
namespace: longhorn-system

# Generate a re-usable name variable for other resources
# configMapGenerator:
#   - name: values
#     files:
#       - values.yaml=values-override.yaml

# Teach kustomize how to update generated names
configurations:
  - kustomizeconfig.yaml
