defaultSettings:
  storageMinimalAvailablePercentage: 10
  upgradeChecker: false
  backupTarget: https://longhornsyxuvhpm.blob.core.windows.net/longhornbackup/ # requires / at end
  backupTargetCredentialSecret: longhorn-azblob-secret
