defaultSettings:
  storageMinimalAvailablePercentage: 10
  upgradeChecker: false
  systemManagedComponentsNodeSelector: "node-role.kubernetes.io/control-plane:false"

defaultBackupStore:
  backupTarget: azblob://longhornbackup@core.windows.net/ # requires / at end
  backupTargetCredentialSecret: longhorn-azblob-credentials
