defaultSettings:
  storageMinimalAvailablePercentage: 10
  upgradeChecker: false
defaultBackupStore:
  backupTarget: azblob://longhornbackup@core.windows.net/ # requires / at end
  backupTargetCredentialSecret: longhorn-azblob-credentials
