# Base kustomization for all app workloads
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - oci-repository.yaml
  - ingress-env.yaml
  - ingress.yaml

# Teach kustomize how to update generated names
configurations:
  - kustomizeconfig.yaml

# components:
#   # Add TLS certificates for ingress
#   - ../../components/ssl-star-ltc-bcit-ca
