# Kustomization for all Apps
#
# - deploy workloads by uncommenting resources below
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  config.fluxcd.io/workload-type: app

resources:
  # - ./common
  # - ./conversion-guide
  # # - ./corgi
  # - ./course-production-site
  # - ./course-workload-estimator
  # # - ./dataset-retriever
  # - ./distribution-game
  # # - ./heme-analyzer-app
  # - ./infrastructure-documentation
  # - ./module-estimator
  # # - ./openlab-scheduler # grouped: in apps_grouped list in Vault
  # # - ./ptracker
  - ./qcon # grouped: in apps_grouped list in Vault
  # - ./sugar-suite
